[application]

# Asset directory
asset_dir = "assets"

[web.app]

# HTML title tag content
title = "dioxus_app"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files (managed by asset! macro in main.rs)
script = []

[web.resource.dev]

# Javascript code file (managed by asset! macro in main.rs)
script = []
